React capstone project - Metrics webapp
Mike111222/my-currencies pull request #6
Opened 2023-08-01 15:36 UTC by Mike111222

I have done the following changes and I want to implement these:

- Use React documentation.
- Use React components.
- Use React props.
- Use React Router.
- Connect React and Redux.
- Handle events in a React app.
- Write integration tests with a React testing library.
- Use styles in a React app.
- Use React life cycle methods.
- Apply React best practices and language style guides in code.
- Use store, actions, and reducers in React.
- Use API to base the development of the webapp on.
- Followed original design idea by [Nelson Sakwa on Behance](https://www.behance.net/sakwadesignstudio).
- Home page with all the currencies.
- Details page with the details of the clicked currency.
- Search bar to search the crypto currencies.
- Followed Technical Requirements.

2023-08-01 16:36 UTC, mukhammadrizooff requested changes
Hi @Mike111222, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-01 16:36 UTC, mukhammadrizooff commented on src/App.css
- [ ] [REQUIRED] Good job so far! I appreciate what you have done but you should give your project `layout(composition)` like the design provided by [Behance](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)) and you should also create other `elements`. Please implement my suggestion 🙏🏼 

![image](https://github.com/Mike111222/crypto-currencies/assets/63915024/dcc05cae-e165-40c6-87da-3825084fa569)

2023-08-02 06:45 UTC, Mike111222 commented on src/App.css
I have done the changes you mentioned. Thanks a lot for the kind feedback.

2023-08-02 14:57 UTC, Mike111222 commented on src/App.css
Please Note: My Render services are not working. I have been trying since this morning but I couldn't connect to Render services. I have notified the Success Team about the issue. The link was working yesterday when I submitted it for the first review. Please approve and I will fix the link later when the Render services issue gets resolved. Thanks

2023-08-02 15:25 UTC, julie-ify approved these changes
Hi @Mike111222,

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-26 14:54 UTC, merged